#include "dak/six_eight/tile.h"

#include <mutex>

namespace dak::six_eight
{
   ////////////////////////////////////////////////////////////////////////////
   //
   // A tile.
   //
   // Can be rotated. Two tiles are the same if they match under some rotation.

   // Description of tiles indexed by their id.
   using rotated_descriptions_t = std::vector<tile_description_t>;
   using rotated_tile_by_ids_t = std::unordered_map<tile_t::id_t, rotated_descriptions_t>;

   std::unordered_map<char, tile_description_t> tile_by_ids =
   {
      { 0, { 1 } },
      { 'a', { 4,
          position_t(0, 0),
          position_t(1, 0),
          position_t(2, 0),
          position_t(2, 1),
          position_t(2, 2),
          position_t(2, 3),
      }},
      { 'A', { 4,
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 0),
          position_t(2, 0),
      }},
      { 'b', { 2,
          position_t(0, 2),
          position_t(0, 3),
          position_t(0, 4),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
      }},
      { 'B', { 2,
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 2),
          position_t(1, 3),
          position_t(1, 4),
      }},
      { 'c', { 4,
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 0),
          position_t(1, 3),
      }},
      { 'd', { 4,
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
      }},
      { 'e', { 4,
          position_t(0, 2),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 0),
      }},
      { 'E', { 4,
          position_t(0, 0),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 2),
      }},
      { 'f', { 4,
          position_t(0, 1),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 0),
          position_t(2, 1),
          position_t(2, 2),
      }},
      { 'F', { 4,
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 2),
      }},
      { 'g', { 4,
          position_t(0, 0),
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
      }},
      { 'G', { 4,
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 0),
          position_t(1, 2),
          position_t(1, 3),
      }},
      { 'h', { 4,
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 2),
          position_t(2, 0),
          position_t(2, 1),
          position_t(2, 2),
      }},
      { 'H', { 4,
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 2),
          position_t(2, 1),
          position_t(2, 2),
      }},
      { 'i', { 4,
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 0),
          position_t(1, 2),
      }},
      { 'I', { 4,
          position_t(0, 0),
          position_t(0, 2),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
      }},
      { 'j', { 4,
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(0, 4),
          position_t(1, 4),
      }},
      { 'J', { 4,
          position_t(0, 4),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(1, 4),
      }},
      { 'k', { 4,
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 3),
      }},
      { 'K', { 4,
          position_t(0, 3),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 0),
          position_t(2, 1),
          position_t(2, 2),
      }},
      { 'l', { 4,
          position_t(0, 1),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 1),
          position_t(2, 2),
      }},
      { 'm', { 2,
          position_t(0, 0),
          position_t(0, 1),
          position_t(1, 0),
          position_t(1, 1),
          position_t(2, 0),
          position_t(2, 1),
      }},
      { 'n', { 2,
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
      }},
      { 'N', { 2,
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
      }},
      { 'o', { 2, 
          position_t(0, 2),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 1),
      }},
      { 'O', { 2,
          position_t(0, 1),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 2),
      }},
      { 'p', { 4,
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(0, 4),
          position_t(1, 2),
      }},
      { 'q', { 4,
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 2),
          position_t(1, 3),
      }},
      { 'Q', { 4,
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
      }},
      { 'r', { 4,
          position_t(0, 1),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(1, 4),
      }},
      { 'R', { 4,
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(0, 4),
          position_t(1, 1),
      }},
      { 's', { 4,
          position_t(0, 0),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 1),
          position_t(2, 2),
      }},
      { 'S', { 4,
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 0),
      }},
      { 't', { 4,
          position_t(0, 0),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 0),
      }},
      { 'u', { 4,
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 2),
      }},
      { 'v', { 4,
          position_t(0, 1),
          position_t(1, 0),
          position_t(1, 1),
          position_t(2, 2),
          position_t(1, 3),
          position_t(2, 1),
      }},
      { 'w', { 4,
          position_t(0, 1),
          position_t(1, 1),
          position_t(2, 0),
          position_t(2, 1),
          position_t(2, 2),
          position_t(2, 3),
      }},
      { 'W', { 4,
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 1),
          position_t(2, 1),
      }},
      { 'x', { 4,
          position_t(0, 2),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 3),
      }},
      { 'X', { 4,
          position_t(0, 3),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 2),
      }},
      { 'y', { 4,
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(0, 4),
          position_t(1, 0),
          position_t(1, 1),
      }},
      { 'Y', { 4,
          position_t(0, 0),
          position_t(0, 1),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(1, 4),
      }},
      { 'z', { 4,
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 1),
          position_t(2, 0),
          position_t(2, 1),
          position_t(2, 2),
      }},
      { 'Z', { 4,
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 1),
          position_t(2, 1),
          position_t(2, 2),
      }},
      { '1', { 4,
          position_t(0, 1),
          position_t(1, 0),
          position_t(1, 1),
          position_t(2, 1),
          position_t(2, 2),
          position_t(2, 3),
      }},
      { '!', { 4,
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 0),
          position_t(1, 1),
          position_t(2, 1),
      }},
      { '2', { 4,
          position_t(0, 0),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 2),
          position_t(2, 3),
      }},
      { '@', { 4,
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 0),
      }},
      { '3', { 4,
          position_t(0, 1),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 0),
          position_t(2, 1),
      }},
      { '#', { 4,
          position_t(0, 0),
          position_t(0, 1),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 1),
      }},
      { '4', { 4,
          position_t(0, 0),
          position_t(0, 1),
          position_t(1, 1),
          position_t(2, 1),
          position_t(2, 2),
          position_t(2, 3),
      }},
      { '$', { 4,
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 1),
          position_t(2, 0),
          position_t(2, 1),
      }},
      { '5', { 4,
          position_t(0, 1),
          position_t(0, 2),
          position_t(1, 0),
          position_t(1, 1),
          position_t(2, 1),
          position_t(2, 2),
      }},
      { '6', { 2,
          position_t(0, 2),
          position_t(0, 3),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 0),
          position_t(2, 1),
      }},
      { '^', { 2,
          position_t(0, 0),
          position_t(0, 1),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 2),
          position_t(2, 3),
      }},
      { '7', { 2,
          position_t(0, 3),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 0),
      }},
      { '&', { 2,
          position_t(0, 0),
          position_t(1, 0),
          position_t(1, 1),
          position_t(1, 2),
          position_t(1, 3),
          position_t(2, 3),
      }},
      { '8', { 2,
          position_t(0, 0),
          position_t(0, 1),
          position_t(0, 2),
          position_t(0, 3),
          position_t(0, 4),
          position_t(0, 5),
      }},
      { '9', { 4,
          position_t(0, 1),
          position_t(1, 1),
          position_t(1, 2),
          position_t(2, 0),
          position_t(2, 1),
          position_t(3, 0),
      }},
      { '(', { 4,
          position_t(0, 0),
          position_t(1, 0),
          position_t(1, 1),
          position_t(2, 1),
          position_t(2, 2),
          position_t(3, 1),
      }},
   };

   static tile_description_t rotate_description(const tile_description_t& a_desc, int a_rotation)
   {
      tile_description_t new_desc = a_desc;
      int min_x = 1000;
      int min_y = 1000;
      for (position_t& pos : new_desc.block_positions) {
         pos.rotate_in_place(a_rotation);
         min_x = std::min(min_x, pos.x());
         min_y = std::min(min_y, pos.y());
      }

      for (position_t& pos : new_desc.block_positions)
         pos = pos.move(-min_x, -min_y);

      std::sort(new_desc.block_positions, new_desc.block_positions + 6);

      return new_desc;

   }

   static void initialize_descriptions(rotated_tile_by_ids_t& descriptions)
   {
      for (const auto&[id, desc] : tile_by_ids) {
         for (int rotation = 0; rotation < desc.possible_rotations; ++rotation) {
            descriptions[id].emplace_back(rotate_description(desc, rotation));
         }
      }
   }

   static rotated_tile_by_ids_t& get_descriptions()
   {
      static rotated_tile_by_ids_t descriptions;
      static std::once_flag flag;
      std::call_once(flag, &initialize_descriptions, descriptions);
      return descriptions;
   }

   tile_description_t tile_t::get_description() const
   {
      return get_descriptions()[my_id][my_rotation];
   }

   /* static */
   const std::vector<tile_t::id_t>& tile_t::get_all_ids()
   {
      static std::vector<tile_t::id_t> ids = {
         'a', 'A', 'b', 'B', 'c', 'd', 'e', 'E', 'f', 'F', 'g', 'G', 'h', 'H', 'i', 'I', 'j', 'J',
         'k', 'K', 'l', 'm', 'n', 'N', 'o', 'O', 'p', 'q', 'Q', 'r', 'R', 's', 'S', 't', 'u', 'v',
         'w', 'W', 'x', 'X', 'y', 'Y', 'z', 'Z', '1', '!', '2', '@', '3', '#', '4', '$', '5',
         '6', '^', '7', '&', '8', '9', '('
      };

      return ids;
   }

}
